version: "3.5"

networks:
  rssagg:
    driver: bridge

volumes:
  postgres:

services:
  database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: rssagg
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d rssagg" ]
      interval: 5s
      timeout: 5s
    network_mode: host
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf